name: Timeout

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 1200s
